language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - sudo apt-get install -qq libprotobuf-dev
  - sudo apt-get install -qq protobuf-compiler
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make && make test
